# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cHRay8bTZllIfr4kuIvNGUewr09_rlZd
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt



img = cv2.imread('img.jpg')
img2 = img[:,:,::-1]
plt.imshow(img2)



#Gray Scale
gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
plt.imshow(gray_image, cmap='gray')



#Cropped Image
cropped_image = gray_image[0:300, 0:300]
plt.imshow(cropped_image, cmap='gray')




image1 = cv2.imread('img.jpg') 
image2 = cv2.imread('sealink.jpg')
image1 = cv2.cvtColor(image1, cv2.COLOR_BGR2RGB)
image2 = cv2.cvtColor(image2, cv2.COLOR_BGR2RGB)
print(image1.shape)
print(image2.shape)



plt.imshow(image1)




plt.imshow(image2)






image2 = cv2.resize(image2, (640,426))
image2.shape





#Add
weightedSum = cv2.addWeighted(image1, 0.5, image2, 0.4, 0)
plt.imshow(weightedSum)





#Sub
sub = cv2.subtract(image1, image2)
plt.imshow(sub)





# Bitwise AND
bitwise_and = cv2.bitwise_and(image2, image1)
plt.imshow(bitwise_and)



# Bitwise OR
bitwise_or = cv2.bitwise_or(image2, image1)
plt.imshow(bitwise_or)




# Bitwise XOR
bitwise_xor = cv2.bitwise_xor(image2, image1)
plt.imshow(bitwise_xor)





# Bitwise NOT
bitwise_not = cv2.bitwise_not(image2)
plt.imshow(bitwise_not)