# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cHRay8bTZllIfr4kuIvNGUewr09_rlZd
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt



img = img = cv2.imread('img.jpg',cv2.IMREAD_GRAYSCALE)
plt.imshow(img,cmap = "gray")



#Basic High Pass Filter
mask = np.ones([3, 3], dtype = int)
mask = mask*-1
mask[2,2]=8
m, n = img.shape
img_new = np.zeros([m, n])
  
for i in range(1, m-1):
    for j in range(1, n-1):
        temp = img[i-1, j-1]*mask[0, 0]+img[i-1, j]*mask[0, 1]+img[i-1, j + 1]*mask[0, 2]+img[i, j-1]*mask[1, 0]+ img[i, j]*mask[1, 1]+img[i, j + 1]*mask[1, 2]+img[i + 1, j-1]*mask[2, 0]+img[i + 1, j]*mask[2, 1]+img[i + 1, j + 1]*mask[2, 2]
         
        img_new[i, j]= temp




plt.imshow(img_new,cmap="gray")



#High Boost Filter
mask1 = mask*-1
mask1[2,2]=9.8
m, n = img.shape
img_new1 = np.zeros([m, n])
  
for i in range(1, m-1):
    for j in range(1, n-1):
        temp1 = img[i-1, j-1]*mask1[0, 0]+img[i-1, j]*mask1[0, 1]+img[i-1, j + 1]*mask1[0, 2]+img[i, j-1]*mask1[1, 0]+ img[i, j]*mask1[1, 1]+img[i, j + 1]*mask1[1, 2]+img[i + 1, j-1]*mask1[2, 0]+img[i + 1, j]*mask1[2, 1]+img[i + 1, j + 1]*mask1[2, 2]
         
        img_new1[i, j]= temp1





plt.imshow(img_new1,cmap="gray")