# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cHRay8bTZllIfr4kuIvNGUewr09_rlZd
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
img = cv2.imread('/content/img.jpg')
img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2_imshow(img)
print("The shape of image is: ",img.shape)
print("Max and min of image: ",img.max(),img.min())


rmin,rmax=img.min(),img.max()
print(rmin,rmax)


smin,smax=0,255


output_img=img.copy()
row,col=img.shape
for i in range(row):
  for j in range(col):
    output_img[i][j]=((255)/(rmax-rmin))*(img[i][j]-rmin)
cv2_imshow(img)
cv2_imshow(output_img)
print(output_img.min(),output_img.max())






input_freq={}
for i in range(256):
  input_freq[i]=0
print(input_freq)

for i in range(img.shape[0]):
  for j in range(img.shape[1]):
    input_freq[img[i][j]]+=1

output_freq={}
for i in range(256):
  output_freq[i]=0
print(output_freq)

for i in range(output_img.shape[0]):
  for j in range(output_img.shape[1]):
    output_freq[output_img[i][j]]+=1








plt.bar(output_freq.keys(), output_freq.values(), color="red")
plt.bar(input_freq.keys(), input_freq.values(), color="blue")
plt.legend(['Output Frequency','Input Frequency'])
plt.xlabel("n")
plt.ylabel("Frequency")
plt.title("Output Frequency")
plt.show()